// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: catalog/v1/catalog.proto

// Пакет синхронного контракта Catalog для межсервисных вызовов (Listing↔Catalog).

package catalogv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetEffectiveAttributesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    string                 `protobuf:"bytes,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEffectiveAttributesRequest) Reset() {
	*x = GetEffectiveAttributesRequest{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEffectiveAttributesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEffectiveAttributesRequest) ProtoMessage() {}

func (x *GetEffectiveAttributesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEffectiveAttributesRequest.ProtoReflect.Descriptor instead.
func (*GetEffectiveAttributesRequest) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *GetEffectiveAttributesRequest) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

type GetEffectiveAttributesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attributes    []*AttributeSpec       `protobuf:"bytes,1,rep,name=attributes,proto3" json:"attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEffectiveAttributesResponse) Reset() {
	*x = GetEffectiveAttributesResponse{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEffectiveAttributesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEffectiveAttributesResponse) ProtoMessage() {}

func (x *GetEffectiveAttributesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEffectiveAttributesResponse.ProtoReflect.Descriptor instead.
func (*GetEffectiveAttributesResponse) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *GetEffectiveAttributesResponse) GetAttributes() []*AttributeSpec {
	if x != nil {
		return x.Attributes
	}
	return nil
}

// AttributeSpec — правило валидации одного атрибута.
type AttributeSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // enum|int|decimal|bool|string
	Required      bool                   `protobuf:"varint,3,opt,name=required,proto3" json:"required,omitempty"`
	Options       []string               `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty"` // slug'и допустимых вариантов для type=enum
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttributeSpec) Reset() {
	*x = AttributeSpec{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributeSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeSpec) ProtoMessage() {}

func (x *AttributeSpec) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeSpec.ProtoReflect.Descriptor instead.
func (*AttributeSpec) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{2}
}

func (x *AttributeSpec) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *AttributeSpec) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AttributeSpec) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *AttributeSpec) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

var File_catalog_v1_catalog_proto protoreflect.FileDescriptor

const file_catalog_v1_catalog_proto_rawDesc = "" +
	"\n" +
	"\x18catalog/v1/catalog.proto\x12\n" +
	"catalog.v1\"@\n" +
	"\x1dGetEffectiveAttributesRequest\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\tR\n" +
	"categoryId\"[\n" +
	"\x1eGetEffectiveAttributesResponse\x129\n" +
	"\n" +
	"attributes\x18\x01 \x03(\v2\x19.catalog.v1.AttributeSpecR\n" +
	"attributes\"m\n" +
	"\rAttributeSpec\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1a\n" +
	"\brequired\x18\x03 \x01(\bR\brequired\x12\x18\n" +
	"\aoptions\x18\x04 \x03(\tR\aoptions2\x81\x01\n" +
	"\x0eCatalogService\x12o\n" +
	"\x16GetEffectiveAttributes\x12).catalog.v1.GetEffectiveAttributesRequest\x1a*.catalog.v1.GetEffectiveAttributesResponseB*Z(bozor/pkg/shared/pb/catalog/v1;catalogv1b\x06proto3"

var (
	file_catalog_v1_catalog_proto_rawDescOnce sync.Once
	file_catalog_v1_catalog_proto_rawDescData []byte
)

func file_catalog_v1_catalog_proto_rawDescGZIP() []byte {
	file_catalog_v1_catalog_proto_rawDescOnce.Do(func() {
		file_catalog_v1_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_catalog_v1_catalog_proto_rawDesc), len(file_catalog_v1_catalog_proto_rawDesc)))
	})
	return file_catalog_v1_catalog_proto_rawDescData
}

var file_catalog_v1_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_catalog_v1_catalog_proto_goTypes = []any{
	(*GetEffectiveAttributesRequest)(nil),  // 0: catalog.v1.GetEffectiveAttributesRequest
	(*GetEffectiveAttributesResponse)(nil), // 1: catalog.v1.GetEffectiveAttributesResponse
	(*AttributeSpec)(nil),                  // 2: catalog.v1.AttributeSpec
}
var file_catalog_v1_catalog_proto_depIdxs = []int32{
	2, // 0: catalog.v1.GetEffectiveAttributesResponse.attributes:type_name -> catalog.v1.AttributeSpec
	0, // 1: catalog.v1.CatalogService.GetEffectiveAttributes:input_type -> catalog.v1.GetEffectiveAttributesRequest
	1, // 2: catalog.v1.CatalogService.GetEffectiveAttributes:output_type -> catalog.v1.GetEffectiveAttributesResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_catalog_v1_catalog_proto_init() }
func file_catalog_v1_catalog_proto_init() {
	if File_catalog_v1_catalog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_v1_catalog_proto_rawDesc), len(file_catalog_v1_catalog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_catalog_v1_catalog_proto_goTypes,
		DependencyIndexes: file_catalog_v1_catalog_proto_depIdxs,
		MessageInfos:      file_catalog_v1_catalog_proto_msgTypes,
	}.Build()
	File_catalog_v1_catalog_proto = out.File
	file_catalog_v1_catalog_proto_goTypes = nil
	file_catalog_v1_catalog_proto_depIdxs = nil
}
